export type MaterialSiteCategory = 'image' | 'video' | 'audio';

export interface MaterialSite {
  name: string;
  url: string;
  logo: string;
  category: MaterialSiteCategory;
  description: string;
  access: '免费' | '免费 / 付费';
  loginRequired: boolean;
  featured?: boolean;
}

const favicon = (domain: string) => `https://www.google.com/s2/favicons?domain=${domain}&sz=64`;

// 官方维护的素材站点清单。普通用户只浏览和跳转，新增、删除和排序由站长在这里管理。
export const materialSites: MaterialSite[] = [
  {
    name: 'Pexels',
    url: 'https://www.pexels.com/zh-cn/',
    logo: '/site-logos/pexels.png',
    category: 'image',
    description: '高质量摄影图片，适合人物、生活方式与商业场景。',
    access: '免费',
    loginRequired: false,
    featured: true,
  },
  {
    name: 'Unsplash',
    url: 'https://unsplash.com/',
    logo: '/site-logos/unsplash.png',
    category: 'image',
    description: '摄影师社区图片库，擅长自然、建筑与氛围画面。',
    access: '免费',
    loginRequired: false,
    featured: true,
  },
  {
    name: 'Pixabay Images',
    url: 'https://pixabay.com/images/',
    logo: '/site-logos/pixabay.png',
    category: 'image',
    description: '图片、插画和矢量素材，题材覆盖范围广。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Freepik',
    url: 'https://www.freepik.com/',
    logo: '/site-logos/freepik.png',
    category: 'image',
    description: '图片、矢量和设计模板，免费与高级内容并存。',
    access: '免费 / 付费',
    loginRequired: true,
  },
  {
    name: 'Burst',
    url: 'https://burst.shopify.com/',
    logo: favicon('burst.shopify.com'),
    category: 'image',
    description: '偏商业、电商和生活方式的免费图片素材。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'StockSnap',
    url: 'https://stocksnap.io/',
    logo: favicon('stocksnap.io'),
    category: 'image',
    description: '可快速浏览的免费摄影素材，适合找封面和配图。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Reshot',
    url: 'https://www.reshot.com/',
    logo: favicon('reshot.com'),
    category: 'image',
    description: '图标、插画和设计素材，适合补充视觉元素。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Wikimedia Commons',
    url: 'https://commons.wikimedia.org/',
    logo: favicon('commons.wikimedia.org'),
    category: 'image',
    description: '公共知识素材库，适合查找历史、百科和资料图。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Pexels Videos',
    url: 'https://www.pexels.com/zh-cn/videos/',
    logo: '/site-logos/pexels.png',
    category: 'video',
    description: '免费实拍视频，适合补充 B-roll 与环境镜头。',
    access: '免费',
    loginRequired: false,
    featured: true,
  },
  {
    name: 'Pixabay Videos',
    url: 'https://pixabay.com/videos/',
    logo: '/site-logos/pixabay.png',
    category: 'video',
    description: '实拍、动画和循环视频素材，支持多种分辨率。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Mixkit Video',
    url: 'https://mixkit.co/free-stock-video/',
    logo: '/site-logos/mixkit.png',
    category: 'video',
    description: '精选免费视频片段，分类清晰，适合快速浏览。',
    access: '免费',
    loginRequired: false,
    featured: true,
  },
  {
    name: 'Coverr',
    url: 'https://coverr.co/',
    logo: '/site-logos/coverr.png',
    category: 'video',
    description: '简洁的免费视频素材库，覆盖商业与生活场景。',
    access: '免费 / 付费',
    loginRequired: false,
  },
  {
    name: 'Videvo',
    url: 'https://www.videvo.net/',
    logo: favicon('videvo.net'),
    category: 'video',
    description: '视频、动效和音频素材库，适合找转场和补镜头。',
    access: '免费 / 付费',
    loginRequired: true,
  },
  {
    name: 'Life of Vids',
    url: 'https://www.lifeofvids.com/',
    logo: favicon('lifeofvids.com'),
    category: 'video',
    description: '偏质感实拍的免费视频素材，适合品牌感画面。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Vidsplay',
    url: 'https://www.vidsplay.com/',
    logo: favicon('vidsplay.com'),
    category: 'video',
    description: '按主题整理的免费视频片段，适合寻找常见场景。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'Motion Array',
    url: 'https://motionarray.com/browse/stock-video/',
    logo: favicon('motionarray.com'),
    category: 'video',
    description: '视频、模板和动态图形资源，适合进阶剪辑项目。',
    access: '免费 / 付费',
    loginRequired: true,
  },
  {
    name: 'Freesound',
    url: 'https://freesound.org/',
    logo: '/site-logos/freesound.png',
    category: 'audio',
    description: '社区音效库，包含环境声、拟音和特殊效果。',
    access: '免费',
    loginRequired: true,
    featured: true,
  },
  {
    name: 'Pixabay Music',
    url: 'https://pixabay.com/music/',
    logo: '/site-logos/pixabay.png',
    category: 'audio',
    description: '背景音乐与音效素材，可按情绪和主题筛选。',
    access: '免费',
    loginRequired: false,
    featured: true,
  },
  {
    name: 'Mixkit Music',
    url: 'https://mixkit.co/free-stock-music/',
    logo: '/site-logos/mixkit.png',
    category: 'audio',
    description: '适合视频制作的免费配乐与分类歌单。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'YouTube 音频库',
    url: 'https://studio.youtube.com/channel/UC/music',
    logo: '/site-logos/youtube.png',
    category: 'audio',
    description: 'YouTube Studio 提供的音乐和音效资源。',
    access: '免费',
    loginRequired: true,
  },
  {
    name: 'Uppbeat',
    url: 'https://uppbeat.io/',
    logo: favicon('uppbeat.io'),
    category: 'audio',
    description: '面向创作者的配乐站点，适合短视频和频道内容。',
    access: '免费 / 付费',
    loginRequired: true,
  },
  {
    name: 'Bensound',
    url: 'https://www.bensound.com/',
    logo: favicon('bensound.com'),
    category: 'audio',
    description: '按风格整理的配乐素材，适合商业和说明类视频。',
    access: '免费 / 付费',
    loginRequired: true,
  },
  {
    name: 'Free Music Archive',
    url: 'https://freemusicarchive.org/',
    logo: favicon('freemusicarchive.org'),
    category: 'audio',
    description: '独立音乐资料库，适合查找不同授权的音乐作品。',
    access: '免费',
    loginRequired: false,
  },
  {
    name: 'SoundBible',
    url: 'https://soundbible.com/',
    logo: favicon('soundbible.com'),
    category: 'audio',
    description: '简单直接的音效站点，适合找常用提示音和环境声。',
    access: '免费',
    loginRequired: false,
  },
];
